sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes
  - "pip install . --process-dependency-links"
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - pyflakes yadage
  - cd tests && pytests && cd ..
  - yadage-validate rootflow.yml from-github/higgsmcproduction
  - "echo 'nevents: 100' > input.yml"
  - yadage-run -t from-github/phenochain workdir_pheno_delphes madgraph_delphes.yml input.yml 
  - find workdir_pheno_delphes
  - cd tests && ./readme_test.sh && cd ..
  - docker build -t lukasheinrich/yadage .
