sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install . --process-dependency-links"
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - pyflakes yadage
  # - (cd tests/scheduler_tests && ./runtests.sh && cd ../../)
  - "echo 'events: 100' > ctx.yml"
  - mkdir workdir_pheno
  - yadage-validate rootflow.yml from-github/higgsmcproduction
  # - yadage-run -t from-github workdir_pheno pheno_workflows/madgraph_delphes.yml ctx.yml -i 60
  # - ls -lrt workdir_pheno
  - docker build -t lukasheinrich/yadage .
  - docker run -it -v /var/run/docker.sock:/var/run/docker.sock lukasheinrich/yadage docker ps -a
