sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install . --process-dependency-links"
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - pyflakes yadage
  - "echo 'events: 100' > ctx.yml"
  - cd tests/scheduler_tests
  - ./runtests.sh
  - cd ../../
  - mkdir workdir_pheno
  - yadage-run -t from-github workdir_pheno pheno_workflows/madgraph_delphes.yml ctx.yml -i 60
  - ls -lrt workdir_pheno
  - docker build -t lukasheinrich/yadage .
