sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install . --process-dependency-links"
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - pyflakes yadage
  - docker build -t lukasheinrich/yadage .
  - "echo 'events: 100' > ctx.yml"
  - mkdir workdir
  - yadage-run -t from-github workdir pheno_workflows/madgraph_delphes.yml ctx.yml -i 60
  - ls -lrt workdir
