sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes
  - "pip install git+git://github.com/lukasheinrich/adage.git@master"
  - "pip install . --process-dependency-links"
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick

script:
  - pyflakes yadage
  - yadage-validate rootflow.yml from-github/higgsmcproduction
  - "echo 'nevents: 100' > input.yml"
  - "echo 'rivet_analysis: MC_GENERIC' >> input.yml"
  - cat input.yml
  - mkdir workdir_pheno
  - yadage-run -t from-github/phenochain workdir_pheno madgraph_rivet.yml input.yml 
  - ls -lrt workdir_pheno
  - docker build -t lukasheinrich/yadage .
  # - docker run -it -v /var/run/docker.sock:/var/run/docker.sock lukasheinrich/yadage docker ps -a
